# Generated by Django 2.2.5 on 2019-09-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mosaic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='test/', verbose_name='File')),
                ('quality', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium')], max_length=1)),
            ],
        ),
    ]
