# Generated by Django 2.2.5 on 2019-09-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosaic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosaic',
            name='quality',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('original', 'Original size')], default='small', max_length=255),
        ),
    ]
