# Generated by Django 2.2.5 on 2019-09-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosaic', '0002_auto_20190914_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosaic',
            name='mosaic_file',
            field=models.FileField(blank=True, upload_to='outputs/'),
        ),
        migrations.AlterField(
            model_name='mosaic',
            name='uploaded_file',
            field=models.FileField(upload_to='inputs/', verbose_name='File'),
        ),
    ]
