# Generated by Django 2.2.5 on 2019-09-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosaic', '0003_auto_20190914_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosaic',
            name='mosaic_file',
            field=models.ImageField(blank=True, upload_to='outputs/'),
        ),
    ]
